In [461]:
import pandas as pd
#pd.options.mode.chained_assignment = None  # default='warn'
import numpy as np
import math

df = pd.read_csv('Dataset_3_sales.csv', sep="|")

delColumn(df, array)
changeIndex(df, 'index')
removeAndModifyUnwantedString(df, 'Item_Fat_Content')
removeSpecifiedString(df, 'Item_Weight', arrayOfStringToRemove)
notInStock(df, 'Item_Visibility')
toNumericAndMean(df, 'Item_Outlet_Sales')
df

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,0,FDA15,9.30,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.138000
1,1,DRC01,5.92,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.422800
2,2,FDN15,17.50,Low Fat,0.01676,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.270000
3,3,FDX07,19.20,Regular,not in stock,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.380000
4,4,NCD19,8.93,Low Fat,not in stock,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.705200
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14199,14199,FDB58,10.50,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,2181.288914
14200,14200,FDD47,7.60,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,2181.288914
14201,14201,NCO17,10.00,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1,2181.288914
14202,14202,FDJ26,15.30,Regular,not in stock,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1,2181.288914
14203,14203,FDU37,9.50,Regular,0.10472,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1,2181.288914

In [462]:
# Nous indique le nombre de valeurs null par colonne
# Toutes les valeurs manquantes sur chaque ligne, on s'aperÃ§oit Ã©galement qu'il y a 
# plusieurs colonnes unnamed que nous allons supprimÃ© car elles n'ont pas de sens
def countNull(dataFrame):
    print(dataFrame.isnull().sum())

countNull(df)

index                           0
Item_Identifier                 0
Item_Weight                     0
Item_Fat_Content               65
Item_Visibility                 0
Item_Type                       0
Item_MRP                        0
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  4016
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

In [429]:
# Retourne le type de chaque ligne
def types(dataFrame):
    return df.dtypes
types(df)

index                          int64
Item_Identifier               object
Item_Weight                  float64
Item_Fat_Content              object
Item_Visibility              float64
Item_Type                     object
Item_MRP                     float64
Outlet_Identifier             object
Outlet_Establishment_Year      int64
Outlet_Size                   object
Outlet_Location_Type          object
Outlet_Type                   object
Item_Outlet_Sales            float64
dtype: object

# Analyse des donnÃ©es et restructuration des donnÃ©es

In [ ]:
# Suppression de toutes les colonnes ayant pour noms 'Unnamed ...' car leurs donnÃ©es Ã©taient infondÃ©es, inutiles et n'avaient 
# pas de sens

# Modification de la colonne item_weight qui contenait quelques String et des valeurs de type Nan, on a fait le 
# choix de transformer toutes les chaines de caractÃ¨res voulu par l'utilisateur en nan et ensuite de modifier ces nan par la 
# moyenn d'item_weight mÃªme si l'on est conscient que Ã§a n'a pas de sens mais pour l'exercice, c'Ã©tait la colonne la 
# adequate pour effectuer la moyenne. 

# Modification Item_Fat_Content, rÃ©cupÃ©ration des valeurs unique, on a pu constater qu'il y avait des doublons et des string 
# 'None', nous avons donc garder une seule valeur de chaque et remplacer les string 'None' par du nan

# Modification d'index, suppression de la colonne index car aprÃ¨s analyse de la colonne on s'est rendu compte qu'il y avait 
# des string, des nan, des doublons ce qui est impossible dans un index. On a donc recrÃ©er cette colonne.

# On a Ã©galement constatÃ© que la colonne Item_visibility contenait de nombreux 0 ce qui signifie d'apres le document que l'item
# ne serait pas disponible en rayant donc pas en stock

In [428]:
def delColumn(dataFrame, arr):
    for i in arr :
        if (i in dataFrame.columns):
            del dataFrame[i]
        else: 
            print(i + ": n'est pas dans le dataFrame")

array = ['Unnamed: 0', 'Unnamed: 0.1', 'Unnamed: 0.1.1', 'Unnamed: 0.1.1.1', 'Unnamed: 0.1.1.1.1', 
         'Unnamed: 0.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1.1', 'Unnamed: 0.1.1.1.1.1.1.1.1']

In [321]:
# Retourne tous les uniques de chaque ligne avec le nomrbe de valeurs manquante
def unique(dataFrame):
    for i in dataFrame.columns:
        print(i + " : " + str(df[i].unique()) + " - valeurs manquantes : " + str(df[i].isnull().sum()))
unique(df)

index : [    0     1     2 ... 14201 14202 14203] - valeurs manquantes : 0
Item_Identifier : ['FDA15' 'DRC01' 'FDN15' ... 'NCF55' 'NCW30' 'NCW05'] - valeurs manquantes : 0
Item_Weight : [ 9.3         5.92       17.5        19.2         8.93       10.395
 13.65       12.79468354 16.2        11.8        18.5        15.1
 17.6        16.35        9.         13.35       18.85       14.6
 13.85       13.          7.645      11.65        5.925      19.25
 18.6        18.7        17.85       10.          8.85        9.8
 13.6        21.35       12.15        6.42       19.6        15.85
  7.39       10.195       9.895      10.895       7.905       9.195
  8.365       7.97       17.7        19.35        8.645      15.6
 18.25        7.855       7.825       8.39       12.85       19.
  5.905       7.76       16.75       15.5         6.055       6.305
 20.85       20.75        8.895      19.7         8.75       13.3
  8.31       19.75       17.1        10.5         6.635      14.15
  8.89        9.1         7.5        16.85        7.485      11.6
 12.65       20.25        8.6        12.6         8.88       20.5
 13.5         7.235       6.92        8.02       12.8        16.6
 14.         16.         21.25        7.365      18.35        5.465
  7.27        6.155      19.5        15.2        14.5        13.1
 12.3        11.1        11.3         5.75       11.35        6.525
 10.3         5.78       11.85       18.75        5.26       16.1
  9.5        13.8        14.65        6.67        6.11       17.2
  6.32        4.88        5.425      14.1         7.55       17.25
 12.         10.1         7.785      13.15        8.5         7.63
  9.285       7.975      15.7         8.985      20.35        6.59
 19.85        6.26       18.2         8.695       7.075       8.195
  7.09        6.095       6.15        9.395      15.75        7.475
  6.445      19.1        15.         16.7         7.07        6.48
  9.695      11.15        9.6        20.7         5.5         7.895
 17.35        7.285       6.17       11.395       7.71       12.1
 14.35        8.1         8.05       16.5         6.785       7.575
  7.47       15.25        7.605      18.         21.2         8.97
 10.6         6.865      10.8        15.15       18.1         6.655
 20.1         7.935      15.35       12.35        6.85        8.775
 14.85        7.84       12.5         8.325       5.765       5.985
 14.3         6.135       8.51        6.65        5.695       6.36
  8.3         7.56        8.71        6.695      14.8        17.75
  8.575       6.57        8.68        5.63        9.13        6.715
  5.82        7.93        5.          7.445       6.675       8.18
  6.98        7.435      20.6         8.355       8.975      20.2
  5.655       5.175      20.          7.67        4.785       8.395
  6.175       8.21        5.845       7.17        8.785       7.89
  5.32        5.03        8.945       6.28        7.565       9.31
  7.02        5.46        6.13        6.55       17.         16.25
  5.15        7.865       6.575       7.06        5.785       7.42
  6.235       6.75        5.86        5.035       6.38        5.675
 11.5        21.         21.1         4.61        7.          6.405
 14.7         7.68        8.185       8.655      10.85        8.42
  7.85        4.59        7.51       11.          6.71       14.75
  7.59        5.155       6.365       8.235       5.365       8.485
  7.535       4.92        6.385       8.26        7.945       8.63
  9.21        6.965       8.905       7.21        7.3         9.27
 10.695       6.215       7.405       7.72        6.115       6.035
  6.78       15.3         7.105       7.52        4.805       6.425
  7.6         6.61        7.325       8.115       5.94        5.635
  7.35        5.825       6.63        7.05        8.315       6.8
  7.035       8.96        5.51        8.43        8.27        7.81
  6.885       5.44        5.405       4.635      10.65        5.735
  6.465       8.84        7.75        6.765       9.065       7.655
  4.615       8.76        7.1         6.195       5.615       8.52
  7.26        6.825       5.325       5.59        5.88        5.19
  6.985       9.06        6.69        8.615       7.275       6.96
  9.17        8.155       5.73        8.935       8.92        7.36
  7.64        5.34        7.22        6.615       6.76        6.3
  5.98        8.06        6.44        5.095       8.8         6.325
  7.31        9.035       9.105       7.145       4.905       4.555
  8.          7.315       6.89        5.945       6.86        6.935
  6.03        7.725       5.885       7.155       6.46        5.48
  8.01        5.8         5.305       6.905       7.96        5.11
  8.77        7.685       8.275       8.38        8.35        9.42
  6.775       6.4         6.895       5.485       6.52        8.67
  5.21        5.4       ] - valeurs manquantes : 0
Item_Fat_Content : ['Low Fat' 'Regular' nan] - valeurs manquantes : 65
Item_Visibility : [0.0160473  0.01927822 0.01676007 ... 0.1429909  0.07352856 0.10472015] - valeurs manquantes : 0
Item_Type : ['Dairy' 'Soft Drinks' 'Meat' 'Fruits and Vegetables' 'Household'
 'Baking Goods' 'Snack Foods' 'Frozen Foods' 'Breakfast'
 'Health and Hygiene' 'Hard Drinks' 'Canned' 'Breads' 'Starchy Foods'
 'Others' 'Seafood'] - valeurs manquantes : 0
Item_MRP : [249.8092  48.2692 141.618  ...  72.8696  82.125  188.053 ] - valeurs manquantes : 0
Outlet_Identifier : ['OUT049' 'OUT018' 'OUT010' 'OUT013' 'OUT027' 'OUT045' 'OUT017' 'OUT046'
 'OUT035' 'OUT019'] - valeurs manquantes : 0
Outlet_Establishment_Year : [1999 2009 1998 1987 1985 2002 2007 1997 2004] - valeurs manquantes : 0
Outlet_Size : ['Medium' nan 'High' 'Small'] - valeurs manquantes : 4016
Outlet_Location_Type : ['Tier 1' 'Tier 3' 'Tier 2'] - valeurs manquantes : 0
Outlet_Type : ['Supermarket Type1' 'Supermarket Type2' 'Grocery Store'
 'Supermarket Type3'] - valeurs manquantes : 0
Item_Outlet_Sales : [3735.138   443.4228 2097.27   ... 3608.636  2778.3834       nan] - valeurs manquantes : 5681

In [444]:
# Fournis des donnÃ©es analytique
def describe(dataFrame):
    return dataFrame.describe()
describe(df)

,index,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales
count,14204.000000,14204.000000,14204.000000,14204.000000,8523.000000
mean,7101.500000,0.065953,141.004977,1997.830681,2181.288914
std,4100.485947,0.051459,62.086938,8.371664,1706.499616
min,0.000000,0.000000,31.290000,1985.000000,33.290000
25%,3550.750000,0.027036,94.012000,1987.000000,834.247400
50%,7101.500000,0.054021,142.247000,1999.000000,1794.331000
75%,10652.250000,0.094037,185.855600,2004.000000,3101.296400
max,14203.000000,0.328391,266.888400,2009.000000,13086.964800

In [460]:
# Fonctions pour convertir une colonne en type float plus remplire les valeurs manquantes (nan) avec la moyenne de cette colonne
def toNumericAndMean(dataFrame, column):
    dataFrame[column] = pd.to_numeric(dataFrame[column])
    values=dataFrame[column].mean()
    dataFrame[column].fillna(value=values, inplace=True)

In [318]:
# Remplace les strings spÃ©cifiÃ©es par le type Nan
def removeSpecifiedString(dataFrame, column, array):
    for i in range(len(dataFrame[column])):
        for j in array :
            if dataFrame[column][i] == j :
                dataFrame[column][i] = np.nan
             
    toFloatAndMean(dataFrame, column)
    
arrayOfStringToRemove = ['Ã¹*Ã¹fsfsf///']

In [430]:
# Nous indique le nombre de valeur unique d'une colonne donnÃ©e
def countUnique(dataFrame, column):
    print(np.count_nonzero(dataFrame[column].unique()))

countUnique(df, 'Item_Fat_Content')

3

In [255]:
# Modifie les strings non voulu d'une colonne donnÃ© avec les strings souhaitÃ©es
def removeAndModifyUnwantedString(dataFrame, column):
    for i in range(len(dataFrame[column])):
        if(dataFrame[column][i] == 'low fat' or dataFrame[column][i] == 'LF'):
            dataFrame[column][i] = 'Low Fat'
        elif dataFrame[column][i] == 'reg' :
            dataFrame[column][i] = 'Regular'
        elif dataFrame[column][i] == 'None': 
            dataFrame[column][i] = np.nan

In [312]:
# supprime la colonne index et la recrÃ©e
def changeIndex(dataFrame, columnName):
    if columnName in dataFrame.columns:
        del dataFrame[columnName]
    if not(columnName in dataFrame.columns):
        dataFrame.insert(0, columnName, 0, allow_duplicates=False)
        for i in range(len(dataFrame)):
            dataFrame[columnName][i] = i

In [450]:
# On remplace les valeurs Ã©gales Ã  0 par une chaine de caractÃ¨res
def notInStock(dataFrame, column):
    for i in range(len(dataFrame)):
        if dataFrame[column][i] == 0:
            dataFrame[column][i] = 'not in stock'

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales,Tier 1,Tier 2,Tier 3
0,0,FDA15,1-10 kg,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380,1,0,0
1,1,DRC01,1-10 kg,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228,0,0,1
2,2,FDN15,15 + kg,Low Fat,0.01676,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700,1,0,0
3,3,FDX07,15 + kg,Regular,no int stock,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800,0,0,1
4,4,NCD19,1-10 kg,Low Fat,no int stock,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14199,14199,FDB58,11-15 kg,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,NaN,1,0,0
14200,14200,FDD47,1-10 kg,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN,0,0,1
14201,14201,NCO17,15 + kg,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1,NaN,0,1,0
14202,14202,FDJ26,15 + kg,Regular,no int stock,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1,NaN,0,1,0
14203,14203,FDU37,1-10 kg,Regular,0.10472,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1,NaN,0,1,0

# Construction de donnÃ©es

In [454]:
# retourne toutes les occurences d'un type d'item donnÃ© par l'utilisateur
def getItemType(dataFrame, itemType):
    dataFrame = dataFrame.loc[dataFrame['Item_Type']==itemType]
    return dataFrame
getItemType(df, 'Canned')

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
29,29,FDC14,12.794684,Regular,0.072222,Canned,43.6454,OUT019,1985,Small,Tier 1,Grocery Store,125.8362
43,43,FDC02,21.350000,Low Fat,0.069103,Canned,259.9278,OUT018,2009,Medium,Tier 3,Supermarket Type2,6768.5228
44,44,FDL50,12.150000,Regular,0.042278,Canned,126.5046,OUT013,1987,High,Tier 3,Supermarket Type1,373.5138
47,47,FDV49,10.000000,Low Fat,0.025880,Canned,265.2226,OUT045,2002,NaN,Tier 2,Supermarket Type1,5815.0972
52,52,FDR13,9.895000,Regular,0.028697,Canned,117.0492,OUT013,1987,High,Tier 3,Supermarket Type1,810.9444
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14153,14153,FDD26,8.710000,Regular,0.072449,Canned,185.2924,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN
14171,14171,FDK26,12.794684,Regular,0.000000,Canned,187.5240,OUT027,1985,Medium,Tier 3,Supermarket Type3,NaN
14194,14194,FDA01,15.000000,Regular,0.054463,Canned,59.5904,OUT049,1999,Medium,Tier 1,Supermarket Type1,NaN
14202,14202,FDJ26,15.300000,Regular,0.000000,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1,NaN
14203,14203,FDU37,9.500000,Regular,0.104720,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1,NaN

In [458]:
# CrÃ©er 3 catÃ©gorie pour le poids
def subCategory(dataFrame, column, value1, value2, value3, palier1, palier2):
        for i in range (len(dataFrame)):
            if type(dataFrame.loc[i, column]) != str :
                if dataFrame.loc[i, column] < palier1 :
                    dataFrame.loc[i, column] = value1
                elif dataFrame.loc[i, column] > palier1 and dataFrame.loc[i, column] < palier2 :
                    dataFrame.loc[i, column] = value2
                else :
                    dataFrame.loc[i, column] = value3
        return dataFrame
                
subCategory(df, 'Item_Weight', '1-10 kg', '11-15 kg', '15 + kg', 10, 15)

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,0,FDA15,1-10 kg,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,1,DRC01,1-10 kg,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,2,FDN15,15 + kg,Low Fat,0.01676,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,3,FDX07,15 + kg,Regular,not in stock,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,4,NCD19,1-10 kg,Low Fat,not in stock,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14199,14199,FDB58,11-15 kg,Regular,0.013496,Snack Foods,141.3154,OUT046,1997,Small,Tier 1,Supermarket Type1,NaN
14200,14200,FDD47,1-10 kg,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN
14201,14201,NCO17,15 + kg,Low Fat,0.073529,Health and Hygiene,118.7440,OUT045,2002,NaN,Tier 2,Supermarket Type1,NaN
14202,14202,FDJ26,15 + kg,Regular,not in stock,Canned,214.6218,OUT017,2007,NaN,Tier 2,Supermarket Type1,NaN
14203,14203,FDU37,1-10 kg,Regular,0.10472,Canned,79.7960,OUT045,2002,NaN,Tier 2,Supermarket Type1,NaN

In [457]:
# get Establishment superior to the year passed by the user
def getEstablishmentByYear(dataFrame, year):
    return df.loc[lambda df: df['Outlet_Establishment_Year'] > year]
getEstablishmentByYear(df, 2007)

,index,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
1,1,DRC01,1-10 kg,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
5,5,FDP36,11-15 kg,Regular,not in stock,Baking Goods,51.4008,OUT018,2009,Medium,Tier 3,Supermarket Type2,556.6088
16,16,NCB42,11-15 kg,Low Fat,0.008596,Health and Hygiene,115.3492,OUT018,2009,Medium,Tier 3,Supermarket Type2,1621.8888
31,31,NCS17,15 + kg,Low Fat,0.080829,Health and Hygiene,96.4436,OUT018,2009,Medium,Tier 3,Supermarket Type2,2741.7644
32,32,FDP33,15 + kg,Low Fat,not in stock,Snack Foods,256.6672,OUT018,2009,Medium,Tier 3,Supermarket Type2,3068.0064
...,...,...,...,...,...,...,...,...,...,...,...,...,...
14159,14159,FDN56,1-10 kg,Regular,0.107493,Fruits and Vegetables,142.5786,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN
14186,14186,DRH36,15 + kg,Low Fat,0.033516,Soft Drinks,72.8696,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN
14187,14187,DRC36,11-15 kg,Regular,0.045168,Soft Drinks,173.4054,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN
14196,14196,FDF46,1-10 kg,Low Fat,0.094053,Snack Foods,116.0834,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN
14200,14200,FDD47,1-10 kg,Regular,0.142991,Starchy Foods,169.1448,OUT018,2009,Medium,Tier 3,Supermarket Type2,NaN

In [463]:
#CrÃ©e trois nouvelles colonnes contenant soit 0 soit 1 selon une condition
def createThreeColumn(dataFrame, baseColumn, value1, value2, value3):
    df[value1] = np.where(df[baseColumn] == value1, '1', '0')
    df[value2] = np.where(df[baseColumn] == value2, '1', '0')
    df[value3] = np.where(df[baseColumn] == value3, '1', '0')
createThreeColumn(df, 'Outlet_Location_Type', 'Tier 1', 'Tier 2', 'Tier 3')